
name: vpn_basic_project
description: PureNet Vpn Project
publish_to: 'none'

# App Version
version: 7.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.7.2

  # Cupertino style icons
  cupertino_icons: ^1.0.8

  # For API Call
  http: ^1.6.0

  # Converting CSV data to List
  csv: ^6.0.0

  # For Lottie Animation
  lottie: ^3.3.2

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads
  google_mobile_ads: ^6.0.0
  flutter_svg: ^2.2.3

  # For firebase
  firebase_core: ^4.2.1

  # For Remote Config
  firebase_remote_config: ^6.1.2

  # For Google Fonts (Comfortaa)
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

dependency_overrides:
  # Fix win32 compatibility with Dart 3.0+
  win32: ^5.15.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/